// Main binding
log = global.log
compile = global.compile
binding = global.binding
fs = global._bindings.fs
buffer = global._bindings.buffer

log("Hello world!")

buff = buffer.new(1024)

fd = fs.open("/tmp/3.txt", fs.flags.O_RDONLY, 438)
if (fd < 0) {
  log("fail!")
  return
}

fs.read(fd, buff, 0, 1024, (err, bytes) {
  log(bytes)
  fs.close(fd)

  buff = buffer.slice(buff, 0, bytes)

  log(buffer.stringify(buff))
})

return { yay: true }
